version: "3.8"

services:
  express-app:
    image: keviinx/express-app
    ports:
      - 8080:8080
    container_name: express-app
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
